baseurl: "/"
languageCode: "en-us"
title: "A minimal Hugo website"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]



menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: Schedule
      url: "schedule/"
      weight: 2
    - name: Homework
      url: "homework/"
      weight: 3
    - name: Syllabus
      url: "yllabus/"
      weight: 4


params:
  description: "A website built through Hugo and blogdown."
  footer: "&copy; [Yihui Xie](https://yihui.org) 2017 -- {Year} | [Github](https://github.com/ochyzh) | [Twitter](https://twitter.com/olga_chyzh)"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
